### PR TITLE
Add horizontal scrolling, add `stickyHeader` prop, & remove Line

### PR DESCRIPTION
**Pull request by KrisLau**
`stickyHeader` prop defaults to true. Line was removed in favor of `borderBottomWidth` since it's better to not have to calculate the width of the line each time. 

Eventually I think the package should probably rewrite the components as functional components as it would be much cleaner code wise.

Related to:

- https://github.com/MuhammadRafeh/react-native-datatable-component/issues/24
- https://github.com/MuhammadRafeh/react-native-datatable-component/issues/16

### CODE REVIEW

**Comment by MuhammadRafeh** [comment]
@KrisLau Thanks for creating the PR and can you please also update the documentation (Readme.md) file

**Comment by KrisLau** [comment]
@MuhammadRafeh Already did

**Comment by MuhammadRafeh** [comment]
Thanks @KrisLau  Let me review this and will merge soon :)

**Comment by MuhammadRafeh** [comment]
Thanks @KrisLau For the PR.

**Pull request merged**
